name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm lint

      - name: Run type check
        run: pnpm typecheck

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Check if version bump is needed
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: version_check
        run: |
          # Skip if commit message contains [skip ci] or is already a version bump
          if [[ "${{ github.event.head_commit.message }}" == *"[skip ci]"* || "${{ github.event.head_commit.message }}" == *"chore: bump version"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Skipping version bump - commit is automated or contains [skip ci]"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Bump version and publish
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.version_check.outputs.skip != 'true'
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch latest changes to avoid conflicts
          git fetch origin main

          # Bump version
          pnpm version patch --no-git-tag-version

          # Commit and push version bump
          git add package.json
          git commit -m "chore: bump version [skip ci]"
          git push origin main

          # Publish to NPM
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
